### ISSUE TITLE
USDT tokens are not authomatically added in the Crystal Wallet of the destination address

### ISSUE THREAD

**Issue by Zhuvikin** [broxus/ton-eth-bridge-relay#1]
**Description:**
After sending USDT tokens from one Free TON wallet to another, the transfered tokens didn't become visible authomatically as requred in the destination Crystall Wallet address.
The token still can be viewed if the root address of USDT is added in the destination wallet manually.

**Expected:**
Amount of recieved USDT should be authomatically visible in the destination address according to the instruction https://broxus.freshdesk.com/support/solutions/articles/80000446930-how-to-add-tip3-token-to-your-crystal-wallet-

![image](https://user-images.githubusercontent.com/4532892/109157749-83c3cb00-7783-11eb-907e-ca7f08f6c2e7.png)

**Comment by Rexagon** [comment]
Fixed in [**1.2.2**](https://github.com/broxus/wallet-desktop/commit/069582ac2e142014512ee33757cd28d17ca2539d)
