### ISSUE TITLE
Unknown values of fields in Collect Tokens popup

### ISSUE THREAD

**Issue by Zhuvikin** [broxus/ton-eth-bridge-relay#2]
**Description:**
Status, confirmations and rejections fields in "Collect Tokens" popup are shown as "unknown" during loading the actual data.

**Expected:**
Show "loading" text or spinner near this fields to get user know that this data is still loading.

![image](https://user-images.githubusercontent.com/4532892/109157921-b79ef080-7783-11eb-8839-08860485bc14.png)

**Comment by Rexagon** [comment]
Fixed in [**1.2.2**](https://github.com/broxus/wallet-desktop/commit/069582ac2e142014512ee33757cd28d17ca2539d)
