### ISSUE TITLE
Questions related to starting up the bridge

### ISSUE THREAD

**Issue by CryptoDevving** [broxus/ton-eth-bridge-relay#6]
Where do I put in the contract addresses? I saw this in the instructions: bridge_address: "0:1d51fb47566d0d283ebbf83c641c01ebebaad6c3cec55895b0074b802036094e" but I am unsure of what to put there. 

How do I enter in token addresses to the bridge as well?

I also am unsure if I can add my own private blockchain to the bridge. Would I just add a custom RPC in place of the polygon RPC? 

Does this bridge need to be installed alongside a node blockchain node for Eth and the custom chain?

**Comment by StelimslimDEV** [comment]
@CryptoDevving It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[BLOCKCHAIN Support](https://exploreonsite.com/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Rexagon** [comment]
Relay itself is only a part of the system. When setting up a new bridge you must deploy its contracts first (using https://github.com/broxus/octusbridge-contracts) and then use the bridge contract address in relays.

Adding a new token is also done via contracts. You need to deploy a new configuration for it (both in Everscale and EVM) and deploy a connector contract to link it with the bridge, and it can then be activated via DAO.

Adding a new EVM network is as simple as adding a new RPC to the config and adding all its required tokens (see above).

For the TVM part (Everscale/Venom) it runs as a light-node so no other RPC is needed. For the EVM and Solana parts it requires third-party RPC.

**Comment by CryptoDevving** [comment]
Thank you for getting back to me so quickly. If I am using polygon edge, I could use it just like any other chain I am bringing to or does that require a special set up as well?

**Comment by Rexagon** [comment]
This relay is used for Everscale/Venom (TVM-based blockchains) <-> EVM and (soon) Everscale/Venom <-> Solana transfers. If you don't need TVM this project may not suit your needs.
